services:
  server:
    build: .
    environment:
      - DB_HOST=172.17.0.1
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: go run main.go -b 0.0.0.0

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data

volumes:
  postgres-database:
